import { Logo } from "@/assets/logo";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { MobileSidebar } from "./_components/mobile-sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "dark")}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="flex items-center justify-center p-4 sm:hidden">
      <MobileSidebar />

      <Link href="/" className="mr-auto -ml-10">
        <Logo className="w-12 h-12" />
      </Link>
    </header>
  );
}
