import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Logo } from "@/assets/logo";
import Link from "next/link";
import { UserIcon } from "@heroicons/react/20/solid";
import { Sidebar } from "./_components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="flex items-center justify-center p-4">
      <Sidebar />

      <Link href="/" className="mr-auto -ml-8">
        <Logo className="w-12 h-12" />
      </Link>
    </header>
  );
}
