name: CI

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: "production"

  KINDE_CLIENT_ID: "lorem ipsum"
  KINDE_CLIENT_SECRET: "lorem ipsum"
  KINDE_ISSUER_URL: "lorem ipsum"
  KINDE_SITE_URL: "lorem ipsum"
  KINDE_POST_LOGOUT_REDIRECT_URL: "lorem ipsum"
  KINDE_POST_LOGIN_REDIRECT_URL: "lorem ipsum"

  POSTGRES_URL: "lorem ipsum"
  POSTGRES_PRISMA_URL: "lorem ipsum"
  POSTGRES_URL_NO_SSL: "lorem ipsum"
  POSTGRES_URL_NON_POOLING: "lorem ipsum"
  POSTGRES_USER: "lorem ipsum"
  POSTGRES_HOST: "lorem ipsum"
  POSTGRES_PASSWORD: "lorem ipsum"
  POSTGRES_DATABASE: "lorem ipsum"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Run Lint
        run: pnpm run lint